apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-deploy
    labels:
      app: app
spec:
    replicas: {{ .Values.env.replicas }}
    selector:
        matchLabels:
            app: app
    strategy:
        canary:
          steps:
          - setWeight: 20
          - pause: {}
          - setWeight: 40
          - pause: {duration: 10}
          - setWeight: 60
          - pause: {duration: 10}
          - setWeight: 80
          - pause: {duration: 10}
    template:
        metadata:
            labels:
                app: app
        spec:
            imagePullSecrets:
                - name: regcred
            containers:
                - name: app
                  image: katiexzhang/oss_implementation_repo:{{ .Values.env.APP_VERSION }}
                  ports:
                    - containerPort: 3000
                  env:
                  - name: NAME
                    value: 'Katie'
                  readinessProbe:
                    httpGet:
                        path: /health
                        port: 3000
                    initialDelaySeconds: 10
                    periodSeconds: 10
                    successThreshold: 1
                    failureThreshold: 3
                  livenessProbe:
                    httpGet:
                        path: /health
                        port: 3000
                    initialDelaySeconds: 10
                    periodSeconds: 10
                    timeoutSeconds: 5
                    successThreshold: 1
                    failureThreshold: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-deploy-dev
    env: dev
    labels:
      app: app-dev
spec:
    replicas: {{ .Values.devEnv.replicas }}
    selector:
        matchLabels:
            app: app-dev
    template:
        metadata:
            labels:
                app: app-dev
        spec:
            imagePullSecrets:
                - name: regcred
            containers:
                - name: app-dev
                  image: katiexzhang/oss_implementation_repo:{{ .Values.devEnv.APP_VERSION }}
                  ports:
                    - containerPort: 3000
                  env:
                  - name: NAME
                    value: 'Katie from Dev'
                  readinessProbe:
                    httpGet:
                        path: /health
                        port: 3000
                    initialDelaySeconds: 10
                    periodSeconds: 10
                    successThreshold: 1
                    failureThreshold: 3
                  livenessProbe:
                    httpGet:
                        path: /health
                        port: 3000
                    initialDelaySeconds: 10
                    periodSeconds: 10
                    timeoutSeconds: 5
                    successThreshold: 1
                    failureThreshold: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-deploy-staging
    env: staging
    labels:
      app: app-staging
spec:
    replicas: {{ .Values.stagingEnv.replicas }}
    selector:
        matchLabels:
            app: app-staging
    template:
        metadata:
            labels:
                app: app-staging
        spec:
            imagePullSecrets:
                - name: regcred
            containers:
                - name: app-staging
                  image: katiexzhang/oss_implementation_repo:{{ .Values.stagingEnv.APP_VERSION }}
                  ports:
                    - containerPort: 3000
                  env:
                  - name: NAME
                    value: 'Katie from Staging'
                  readinessProbe:
                    httpGet:
                        path: /health
                        port: 3000
                    initialDelaySeconds: 10
                    periodSeconds: 10
                    successThreshold: 1
                    failureThreshold: 3
                  livenessProbe:
                    httpGet:
                        path: /health
                        port: 3000
                    initialDelaySeconds: 10
                    periodSeconds: 10
                    timeoutSeconds: 5
                    successThreshold: 1
                    failureThreshold: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-deploy-prod
    env: prod
    labels:
      app: app-prod
spec:
    replicas: {{ .Values.prodEnv.replicas }}
    selector:
        matchLabels:
            app: app-prod
    template:
        metadata:
            labels:
                app: app-prod
        spec:
            imagePullSecrets:
                - name: regcred
            containers:
                - name: app-prod
                  image: katiexzhang/oss_implementation_repo:{{ .Values.prodEnv.APP_VERSION }}
                  ports:
                    - containerPort: 3000
                  env:
                  - name: NAME
                    value: 'Katie from Prod'
                  readinessProbe:
                    httpGet:
                        path: /health
                        port: 3000
                    initialDelaySeconds: 10
                    periodSeconds: 10
                    successThreshold: 1
                    failureThreshold: 3
                  livenessProbe:
                    httpGet:
                        path: /health
                        port: 3000
                    initialDelaySeconds: 10
                    periodSeconds: 10
                    timeoutSeconds: 5
                    successThreshold: 1
                    failureThreshold: 3
