name: CI/CD

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKER_KEY }}
  IMAGE_NAME: oss_implementation_repo

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run Helm chart tests
        run: ct install --chart-dirs app/helm

  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_KEY }}

      - name: Build Docker image
        run: |
          cd app
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Push Docker image
        run: |
          cd app
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy-to-dev:
    environment: dev
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Update values-dev.yaml
        run: |
          cd app/helm
          sed -i 's|APP_VERSION:.*|APP_VERSION: '${{ github.sha }}'|' values-dev.yaml
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values-dev.yaml
          git commit -m "Update values-dev.yaml"
          git push

  deploy-to-staging:
    environment: staging
    runs-on: ubuntu-latest
    needs: deploy-to-dev
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Update values-staging.yaml
        run: |
          git pull
          cd app/helm
          sed -i 's|APP_VERSION:.*|APP_VERSION: '${{ github.sha }}'|' values-staging.yaml
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values-staging.yaml
          git commit -m "Update values-staging.yaml"
          git push

  deploy-to-prod:
    environment: prod
    runs-on: ubuntu-latest
    needs: deploy-to-staging
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Update values-prod.yaml
        run: |
          git pull
          cd app/helm
          sed -i 's|APP_VERSION:.*|APP_VERSION: '${{ github.sha }}'|' values-prod.yaml
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values-prod.yaml
          git commit -m "Update values-prod.yaml"
          git push
